# Generated by Django 5.1.2 on 2025-03-10 22:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date=models.DateTimeField(default=django.utils.timezone.now)),
        ),
    ]
